#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch armv7s -isysroot /Applications/XCode5/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk -Wno-unused-value -Wno-parentheses"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Wed Feb 26 09:59:50 CST 2014"
#endif
